      SUBROUTINE INVERS(A,RF,B1,L1,B2,L2,FAZ,BAZ,S,IT,SIG,LAM,LQ,KIND)
C
C     LATITUDE POSITIVE NORTH, LONGITUDE POSITIVE EAST, AZIMUTH CLOCK-
C     WISE FROM NORTH.  ANGLES IN RADIAN MEASURE.
C     A GENERAL INVERSE FORMULA FOR STANDARD AND ANTIPODAL CASES.
C     LATITUDE MAY BE 90 DEGREES EXACTLY.
C     PROGRAMMED BY T. VINCENTY, NOVEMBER 1975
C     MODIFIED FOR BACK SIDE SOLUTIONS, SEPT. 1976
C
      DOUBLE PRECISION X,TEM1,TEM2
      DOUBLE PRECISION A,RF,B1,L1,B2,L2,FAZ,BAZ,S,L,BOA,D,
     *SINU1,COSU1,SINU2,COSU2,PI,TEST,LAM,SINLAM,COSLAM,TEMP,
     * SINSIG,COSSIG, SIG, SINAL,SCOSAL,COSTM,C,K,E, PREV
      DATA PI/3.141592653590D0/, TRIFLE/.1E-13/
      BOA =  1.-1./RF
      D = DSQRT((BOA*DSIN(B1))**2+DCOS(B1)**2)
      SINU1 = BOA*DSIN(B1)/D
      COSU1 = DSQRT(-SINU1**2+1.)
      D = DSQRT((BOA*DSIN(B2))**2+DCOS(B2)**2)
      SINU2 = BOA*DSIN(B2)/D
      COSU2 = DSQRT(-SINU2**2+1.)
      L = L2-L1
      IF(L.GT.PI)L=L-PI-PI
      IF(L.LT.-PI)L=L+PI+PI
      PREV = L
      TEST = L
      IT =-1
      KIND=1
      LAM=L
    2 SINLAM = DSIN(LAM)
      IF(DABS(PI-DABS(L))  .LT..2E-10) SINLAM= 0.
      COSLAM = DCOS(LAM)
    8 TEMP = COSU1*SINU2-SINU1*COSU2*COSLAM
      SINSIG = DSQRT((COSU2*SINLAM)**2+TEMP**2)
      IF(LQ.EQ.1)SINSIG=-SINSIG
      COSSIG = SINU1*SINU2+COSU1*COSU2*COSLAM
      SIG = DATAN2(SINSIG,COSSIG)
      IF(LQ.EQ.1)SIG=SIG+PI+PI
      GO TO (3,5),KIND
    3 SINAL = COSU1*COSU2*SINLAM/SINSIG
      SCOSAL = -SINAL**2+1.
    4 COSTM = -2.*SINU1*SINU2/(SCOSAL+TRIFLE)+COSSIG
      IT=IT+1
      IF(KIND.EQ.2) IT=IT-2
      GO TO (5,6),KIND
    5 C = ((-3.*SCOSAL+4.)/RF+4.)*SCOSAL/RF/16.
      GO TO (15,16), KIND
   16 IF(DABS(SINAL-PREV).LT.TRIFLE) GO TO 100
   15 GO TO (6,4),KIND
    6 D=(((2.*COSTM**2-1.)*COSSIG*C+COSTM)*SINSIG*C+SIG)*(1.-C)/RF
      GO TO (7,9),KIND
    7 LAM=L+D*SINAL
      IF(DABS(LAM-TEST).LT.TRIFLE) GO TO 100
      IF(L.LT.0.)LAM=-LAM
      IF(LQ.EQ.1.AND.LAM.LT.0.)GO TO 200
      IF(L.LT.0.)LAM=-LAM
      IF(            DABS(LAM).GT.PI) GO TO 200
      IF(((LAM-TEST)*(TEST-PREV)).LT.0..AND.IT.GT.5)LAM=(2.*LAM+3.*TEST
     * +PREV)/6.
      PREV = TEST
      TEST = LAM
      GO TO 2
  200 KIND=2
      IT= 1
      LAM= PI
      IF(LQ.EQ.1)LAM=0.
      IF(L.LT.0.) LAM=-LAM
      SINAL = 0.
      SCOSAL = 1.
      TEST = 2.
      PREV = TEST
      SIG = PI - DABS(DATAN(SINU1/COSU1) + DATAN(SINU2/COSU2))
      IF(LQ.EQ.1)SIG=-SIG+PI+PI
      SINSIG = DSIN(SIG)
      COSSIG = DCOS(SIG)
      GO TO 5
    9 SINAL= (LAM-L)/D
      IF(((SINAL-TEST)*(TEST-PREV)).LT.0..AND.IT.LT.-2)SINAL=(2.*SINAL
     * +3.*TEST +PREV)/6.
      PREV = TEST
      TEST = SINAL
      SCOSAL= -SINAL**2+1.
      SINLAM= SINAL*SINSIG/(COSU1*COSU2)
      COSLAM = -DSQRT(DABS(-SINLAM**2 +1.))
      IF(LQ.EQ.1)COSLAM=-COSLAM
      LAM= DATAN2(SINLAM,COSLAM)
      GO TO 8
  100 IF(KIND.EQ.2) GO TO 11
      TEM1=COSU2*SINLAM
      TEM2=COSU1*SINU2-SINU1*COSU2*COSLAM
      IF(LQ.EQ.1)TEM1=-TEM1
      IF(LQ.EQ.1)TEM2=-TEM2
      FAZ=DATAN2(TEM1,TEM2)
      TEM1=-COSU1*SINLAM
      TEM2=SINU1*COSU2-COSU1*SINU2*COSLAM
      IF(LQ.EQ.1)TEM1=-TEM1
      IF(LQ.EQ.1)TEM2=-TEM2
      BAZ=DATAN2(TEM1,TEM2)
      GO TO 12
   11 FAZ= SINAL/COSU1
      BAZ= DSQRT(-FAZ**2+1.)
      IF(LQ.NE.1 .AND. TEMP.LT.0.)BAZ=-BAZ
      IF(LQ.EQ.1 .AND. TEMP .GT.0.)BAZ=-BAZ
      FAZ= DATAN2(FAZ,BAZ)
      TEM1=-SINAL
      TEM2=SINU1*SINSIG-COSU1*COSSIG*BAZ
      BAZ=DATAN2(TEM1,TEM2)
   12 IF(FAZ.LT.0.)FAZ= FAZ+PI+PI
      IF(BAZ.LT.0.) BAZ= BAZ+PI+PI
      E= COSTM**2*2.-1.
      K     = DSQRT((1./BOA**2-1.)*SCOSAL+1.)+1.
      K     = (K-2.)/K
      C     = (K*K/4.+1.)/(1.-K)
      D     = (-.375*K*K+1.)*K
      S     = ((((E+E-1.)*(SINSIG**2*4.-3.)*COSTM*(-D)/6.+E*COSSIG)*D/4.
     *        +COSTM)*SINSIG*(-D)+SIG)*C*A*BOA
      IF(KIND.EQ.1) IT = IABS(IT)
      RETURN
      END
